apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mrasif
  name: mrasif
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mrasif
  template:
    metadata:
      labels:
        app: mrasif
    spec:
      containers:
        - name: mrasif
          image: mrasif/mrasif.in:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: svc
