apiVersion: v1
kind: Service
metadata:
  name: mrasif
spec:
  selector:
    app: mrasif
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
