apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mrasif-in
  name: mrasif-in
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: mrasif-in
  template:
    metadata:
      labels:
        app: mrasif-in
    spec:
      containers:
        - name: mrasif-in
          image: mrasif/mrasif.in:{{ .Values.image.tag }}
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: 3000
              name: svc
