apiVersion: v1
kind: Service
metadata:
  name: mrasif-in
spec:
  selector:
    app: mrasif-in
  type: { { .Values.service.type } }
  ports:
    - name: http
      protocol: TCP
      port: { { .Values.service.port } }
      targetPort: 3000
